services:
  - type: web
    name: gas-backend
    env: node
    region: oregon # or choose a region close to you
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 5000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SERVICE_ROLE_KEY
        sync: false
